version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
